# Generated by Django 5.2.9 on 2026-01-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_blog', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('content_blog', models.TextField()),
                ('image_blog', models.ImageField(upload_to='images/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_publication', models.BooleanField(default=True)),
                ('views_blog', models.IntegerField()),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'страницы блога',
                'ordering': ['is_publication'],
            },
        ),
    ]
