# Generated by Django 5.2.9 on 2026-01-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views_blog',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
